name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
      
  tests:

    runs-on: self-hosted
    container:
        image: ubuntu:bionic
    steps:
      - name: Run experiments
        run: |
          source pippo.sh
