name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
      
  tests:

    runs-on: self-hosted
    container:
        image: ubuntu:bionic
        options: "--entrypoint /bin/bash"
    steps:
      - name: Run experiments
        run: |
          cd ..
          source pippo.sh
        shell: bash
